### ISSUE TITLE
BUG: Page renames aren't updated for page change actions

### ISSUE THREAD

**Issue by v4u6h4n** [StreamController/DeckPlugin#1]
**Describe the bug**
There seems to be a bug where if I rename a page it isn't updated for pages change actions that have been assigned that page.

EDIT: Although not related to the import function, it seriously effects its usefulness as renaming the pages is kinda the first thing I wanted to do after the import, cause its indecipherable as just numbered pages.

**Comment by Core447** [comment]
d155dd5bad612968f9dc941581c99652c8bc9cd4 should fix this. Can you please update the plugin, restart the app (just to make sure) and try again?

**Comment by v4u6h4n** [comment]
Oh that's where this issue went lol

Okay that seems like it's fixed now, thanks :-)

**Comment by v4u6h4n** [comment]
I don't know if this is a problem, but I'm seeing a lot of errors in the terminal when renaming stuff. I'm not noticing any issues though, it all seems to be working okay.

**Comment by Core447** [comment]
You're getting a lot of errors because the page is None. This is weird. Might be fixed with 7a6382a87dd88c54fa50e3b98e8564672fbe7197

**Comment by v4u6h4n** [comment]
I had a lot of broken ones from the previous versions, so took me a while to see the results, but seems fixed now. Such a relief. Well, I think, at least tentatively, that the import function is now stable enough to be recommended for your average user. Thanks for the help ;-)
