### ISSUE TITLE
Feature Request: Alphabetical ordering of page names in page change drop action drop down

### ISSUE THREAD

**Issue by v4u6h4n** [StreamController/DeckPlugin#2]
Currently the ordering seems to be append renamed, or new pages.

**Comment by Core447** [comment]
Added in [90d37](https://github.com/StreamController/StreamController/commit/90d376292cb9a2200afeef5bc207adad8c334a62)

**Comment by v4u6h4n** [comment]
I'm seeing the same behaviour again since updating.

**Comment by Core447** [comment]
Are you still on main? The Flatpak doesn't have this patch yet

**Comment by v4u6h4n** [comment]
Yeah I'm still on main. It might be linked to the crash from the other issue. Because it comes and goes. I'll keep an eye on it. I'm going to switch back to running it with from terminal in case the logging doesn't catch it.

**Comment by Core447** [comment]
Ok, yes unfortunately not everything gets logged
